BlockMatrix lmmreg
johnc1231/hail pull request #15
Opened 2017-08-15 00:56 UTC by jbloom22

- added LinearMixedRegresionDist and related
- added Dist tests in testSmall and testLDandRRMLOCO
- added Dist version of Eigen
- split apart full rank and low rank RDD transformations
- pushed blocked math down further in FullRank
- removed blocking in low rank
- pulled up reused matrices in low rank
- factored out globalFit function

2017-08-16 04:04 UTC, johnc1231 requested changes
This looks awesome Jon.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/KinshipMatrix.scala
> +    val K = matrix.toLocalMatrix().asBreeze().asInstanceOf[DenseMatrix[Double]]
Why change this? Not a big deal since it's equivalent in this case, but toDenseMatrix on a DenseMatrix just casts to a DenseMatrix anyway.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/KinshipMatrix.scala
> +    val eigK = printTime(eigSymD(K))
We should remember to take these print times out before merging for real. I only included it in mine for the sake of experimenting.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/stats/Eigendecomposition.scala
> +  require(evects.numRows() == rowIds.length) // FIXME: expensive
Not actually expensive. When you created the distributed U from local U, you used `BlockMatrixIsDistributedMatrix.from`. That constructs a BlockMatrix while specifying number of rows and columns, so accessing numRows() here is actually instantaneous.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
>        fatal("Bad stuff")
We should be more specific here so that if a bug causes this to happen we get a message about what actually went wrong.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
>      val sampleMask = vds.sampleIds.map(completeSamplesSet).toArray
We only technically need sampleMask if runAssoc is true. Should we move it down into the conditional for that?

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
>      val sampleMask = vds.sampleIds.map(completeSamplesSet).toArray
Actually, this is true for completeSamplesSet  and completeSampleIndex as well.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
> +trait ScalarLMM
Doesn't seem like there is any point in having the trait anymore. FullRankScalarLMM and LowRankScalarLmm no longer share an interface.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
> +    val b = CdC \ Cdy
Think you need a try catch here or you run risk of `MatrixSingularException`

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/stats/ComputeRRM.scala
> +        vds.rdd.map { case (v, (va, gs)) => IndexedRow(variantIdxBc.value(v), Vectors.dense(RegressionUtils.hardCalls(gs, n, sampleMask).toArray)) } // FIXME: handle sparse?
Think we can manage this without broadcasting the variant index. Can't we just `zipWithIndex` and work from there? The variants are already in order as per `OrderedRDD` backing the VDS (at least I'm pretty sure that's always the case). Just seems unnecessary to broadcast what could be kind of a big thing if there are a ton of variants.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +    val sampleMask = vds.sampleIds.map(completeSamplesSet).toArray
As I said on regular LMMReg, seems this stuff is only necessary if runAssoc is true. Maybe move it down?

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +      fatal("Bad stuff")
More descriptive error needed.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +    val Ut = evects.transpose
Confirm this with Dan, but I think that that just as using `multiply` is worse than using `*` on BlockMatrices now,  I think using `transpose` is worse than using `t` as imported from `DistributedMatrix`.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +object Helper {
If you are going to keep this named Helper, it cannot have global scope the way it does here. It should probably be inside the `LinearMixedRegressionDist` object anyway, regardless of name.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +          val projG = (allG.toBlockMatrixDense() * (Ut :* diagLMM.sqrtInvD.toArray).transpose)
Don't use transpose, see above.

2017-08-16 04:04 UTC, johnc1231 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +          val projG = (allG.toBlockMatrixDense() * Ut.transpose)
Don't use transpose, see above.

2017-08-16 15:25 UTC, jbloom22 commented on src/main/scala/is/hail/methods/KinshipMatrix.scala
> +    val K = matrix.toLocalMatrix().asBreeze().asInstanceOf[DenseMatrix[Double]]
asBreeze returns Matrix, and toDenseMatrix on Matrix doesn't just cast:
```
  def toDenseMatrix(implicit cm: ClassTag[V], zero: Zero[V]) = {
    DenseMatrix.tabulate(rows, cols){ (i,j) => apply(i, j)}
  }
```

2017-08-16 15:26 UTC, jbloom22 commented on src/main/scala/is/hail/methods/KinshipMatrix.scala
> +    val K = matrix.toLocalMatrix().asBreeze().asInstanceOf[DenseMatrix[Double]]
I could change asBreeze to additionally cast to Dense or Sparse, so this wouldn't be needed in other places. Thoughts?

2017-08-16 15:26 UTC, jbloom22 commented on src/main/scala/is/hail/methods/KinshipMatrix.scala
> +    val eigK = printTime(eigSymD(K))
Yes, but will leave for now as we need to do scaling tests

2017-08-16 15:42 UTC, jbloom22 commented on src/main/scala/is/hail/stats/Eigendecomposition.scala
> +  require(evects.numRows() == rowIds.length) // FIXME: expensive
Yes, and it looks like same is true after BlockMatrix mult, so I've removed the FIXME

2017-08-16 15:49 UTC, jbloom22 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
>      val sampleMask = vds.sampleIds.map(completeSamplesSet).toArray
completeSampleSet is needed for the local case when subsetting the eigendecomposition. But I moved the others down.

2017-08-16 16:06 UTC, jbloom22 commented on src/main/scala/is/hail/methods/LinearMixedRegression.scala
>        fatal("Bad stuff")
good catch. of course I didn't mean to keep "bad stuff", but I overlooked it!

2017-08-16 20:34 UTC, jbloom22 commented on src/main/scala/is/hail/methods/LinearMixedRegressionDist.scala
> +object Helper {
for now i've moved the methods inside LinearMixedRegressionDist

2017-08-17 01:39 UTC, jbloom22 commented
I've addressed your comments, incorporated IntOrderedPartitioner, moved LinearMixedRegressionDist into LinearMixedRegression, done some renaming, and built more Python interfaces so I can start testing, etc

2017-08-18 14:47 UTC, merged